### PR TITLE
Rebase to alpine 3.17 with php8.1

### PR DESCRIPTION
**Pull request by nemchik**

### CODE REVIEW

**Comment by thespad** [comment]
CI needs fixing up with the right password so it doesn't 403.

**Comment by nemchik** [comment]
I've been looking at this for a bit and I can't figure out what password it needs 😓

**Comment by thespad** [comment]
The live image works without a password (even if you set the env, which seems like it should be a problem), the PR gives a 403 regardless.

**Comment by thespad** [comment]
root/etc/s6-overlay/s6-rc.d/init-librespeed-config/up is empty so the init is never running. Would probably explain it.

**Comment by nemchik** [comment]
that fixed it...

**Review by thespad — APPROVED** [review]

**Pull request merged**
